In [7]:
from array import array

'''Write a Python program to get the number of occurrences of a specified element in an
array.
Sample Output:
Original array: array(&#39;i&#39;, [1, 3, 5, 3, 7, 9, 3])
Number of occurrences of the number 3 in the said array: 3'''

def count_occurrences(arr, target):
    # Convert the array to a list to use count() method
    arr_list = list(arr)
    # Count the occurrences of the target element
    occurrences = arr_list.count(target)
    return occurrences

# Define the original array
original_array = array('i', [1, 3, 5, 3, 7, 9, 3])

# Element to count occurrences
element_to_count = 3

# Get the number of occurrences of the specified element
num_occurrences = count_occurrences(original_array, element_to_count)

# Display the result
print("Original array:", original_array)
print(f"Number of occurrences of the number {element_to_count} in the said array:", num_occurrences)


Original array: array('i', [1, 3, 5, 3, 7, 9, 3])
Number of occurrences of the number 3 in the said array: 3


In [8]:
import numpy as np

def count_occurrences(arr, elem):
    return np.count_nonzero(arr == elem)

# Sample array
my_array = np.array([1, 3, 5, 3, 7, 9, 3])
element_to_count = 3

# Count occurrences
result = count_occurrences(my_array, element_to_count)

# Display the result
print(f"Original array: array({my_array})")
print(f"Number of occurrences of the number {element_to_count} in the array: {result}")

Original array: array([1 3 5 3 7 9 3])
Number of occurrences of the number 3 in the array: 3


In [9]:
from array import array

def extend_array(arr, iterable):
    arr.extend(iterable)
    return arr

# Define the original array
original_array = array('i', [1, 3, 5, 7, 9])

# Iterable to append
items_to_append = [1, 3, 5, 7, 9]

# Extend the original array with items from the iterable
extended_array = extend_array(original_array, items_to_append)

# Display the result
print("Original array:", original_array)
print("Extended array:", extended_array)


Original array: array('i', [1, 3, 5, 7, 9, 1, 3, 5, 7, 9])
Extended array: array('i', [1, 3, 5, 7, 9, 1, 3, 5, 7, 9])


In [38]:
import numpy as np

arr = np.arange(1,10)
arr = arr.reshape(3,3)

print("Original array:",arr)

Original array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
import numpy as np

original_list = [12.23, 13.32, 100, 36.32]
numpy_array = np.array(original_list)
print("Original List:", original_list)
print("One-dimensional NumPy array:", numpy_array)

print(type(numpy_array))

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]
<class 'numpy.ndarray'>


In [44]:
import numpy as np

arr = np.array(([1, 2, 3,]), dtype=np.int64)
print("Size of the array:", arr.size)
print("Length of one array element in bytes:", arr.itemsize, np.int64)
print("Total bytes consumed by the elements of the array:", arr.nbytes)


Size of the array: 3
Length of one array element in bytes: 8 <class 'numpy.int64'>
Total bytes consumed by the elements of the array: 24


In [12]:
import numpy as np

A = np.array([[3, 7], [2, 4]])
result = A * 5
print("Scalar multiplied matrix:")
print(result)


Scalar multiplied matrix:
[[15 35]
 [10 20]]


In [13]:
import numpy as np

u = np.array([3, -2])
v = np.array([5, 1])
result = np.dot(u, v)
print("Dot product of u and v:", result)


Dot product of u and v: 13


In [14]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result = np.dot(A, B)
print("Matrix multiplication result:")
print(result)


Matrix multiplication result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [15]:
import numpy as np

M = np.array([[4, 2, 1], [1, 3, 0], [2, 1, 5]])
x = np.array([2, -1, 3])
result = np.dot(M, x)
print("Matrix-vector product result:")
print(result)


Matrix-vector product result:
[ 9 -1 18]


In [16]:
import numpy as np

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generating the first 20 prime numbers
primes = []
num = 2
while len(primes) < 20:
    if is_prime(num):
        primes.append(num)
    num += 1

primes_array = np.array(primes)
sum_of_primes = np.sum(primes_array)
print("Array of the first 20 prime numbers:")
print(primes_array)
print("Sum of the elements in the array:", sum_of_primes)


Array of the first 20 prime numbers:
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71]
Sum of the elements in the array: 639


In [1]:
!pip install pandas

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/11/17/fb1a34f3e73debbc2fd15a01ea17eaab3717943d08463ff4979a4f024b3f/pandas-2.1.4-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
  Obtaining dependency information for tzdata>=2022.1 from https://files.pythonhosted.org/packages/a3/fb/52b62131e21b24ee297e4e95ed41eba29647dad0e0051a92bb66b43c70ff/tzdata-2023.4-py2.py3-none-any.whl.metadata
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   -------------------


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\HELLO\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
!pip install matplotlib

  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/26/5a/27fd341e4510257789f19a4b4be8bb90d1113b8f176c3dab562b4f21466e/matplotlib-3.8.2-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/ca/2a/d197a412ec474391ee878b1218cf2fe9c6e963903755887fc5654c06636a/contourpy-1.2.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for cycler>=0.10 from https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl.metadata
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/d2/54/26919780384c6dd9c3108c5ca64bbe8af45ce567e2f2493cd0cb8c596b9a/fonttools-4.47.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/160.4 kB ? eta -:--:--
     ---------------------------------------- 0.0/160.4 kB ? eta -:--


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\HELLO\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [5]:
!pip install tkinter


ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\HELLO\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
import tkinter as tk
from tkinter import ttk

def sign_up():
    username = username_entry.get()
    email = email_entry.get()
    password = password_entry.get()
    
    # Add your sign-up logic here
    
    # For this example, let's print the entered details
    print(f"Username: {username}")
    print(f"Email: {email}")
    print(f"Password: {password}")

root = tk.Tk()
root.title("Social Media Sign-Up")

# Creating a frame with a glassmorphism-like effect
style = ttk.Style()
style.theme_use('clam')  # Choosing a basic theme for this example
style.configure('TFrame', background='#f0f0f0')  # Set the background color

frame = ttk.Frame(root, style='TFrame', padding=20)
frame.pack(padx=20, pady=20)

# Labels and Entries
username_label = ttk.Label(frame, text="Username:")
username_label.grid(row=0, column=0, sticky=tk.W)

username_entry = ttk.Entry(frame)
username_entry.grid(row=0, column=1)

email_label = ttk.Label(frame, text="Email:")
email_label.grid(row=1, column=0, sticky=tk.W)

email_entry = ttk.Entry(frame)
email_entry.grid(row=1, column=1)

password_label = ttk.Label(frame, text="Password:")
password_label.grid(row=2, column=0, sticky=tk.W)

password_entry = ttk.Entry(frame, show="*")
password_entry.grid(row=2, column=1)

sign_up_button = ttk.Button(frame, text="Sign Up", command=sign_up)
sign_up_button.grid(row=3, columnspan=2, pady=10)

root.mainloop()


In [17]:
import numpy as np

temperatures = np.array([25.5, 26.2, 24.8, 23.5, 27.0, 25.9, 28.3])

mean_temp = np.mean(temperatures)
print("Mean temperature:", mean_temp)

above_mean_indices = np.where(temperatures > mean_temp)[0]
print("Indices where temperature is above the mean:", above_mean_indices)


Mean temperature: 25.88571428571429
Indices where temperature is above the mean: [1 4 5 6]


In [18]:
import numpy as np

arr = np.arange(10, 51)
extracted_elements = arr[5:16]
print("Extracted elements from index 5 to index 15:", extracted_elements)


Extracted elements from index 5 to index 15: [15 16 17 18 19 20 21 22 23 24 25]


In [19]:
import numpy as np

matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

submatrix = matrix[1:3, 1:3]
print("Submatrix formed by central 2x2 elements:")
print(submatrix)


Submatrix formed by central 2x2 elements:
[[ 6  7]
 [10 11]]


In [20]:
import numpy as np

random_array = np.random.rand(5, 5)
diagonal_elements = np.diagonal(random_array)
print("Diagonal elements as a 1D array:")
print(diagonal_elements)


Diagonal elements as a 1D array:
[0.29734781 0.11146877 0.29520652 0.45747563 0.30056851]


In [21]:
import numpy as np

tensor = np.random.rand(3, 4, 5)
subarray = tensor[1:3, 0, :]
print("Subarray containing elements from the specified rows:")
print(subarray)


Subarray containing elements from the specified rows:
[[0.06321694 0.5508797  0.62515279 0.27466783 0.17351894]
 [0.17927679 0.89706179 0.10436186 0.75773667 0.20375631]]


In [22]:
import numpy as np

data = np.array([10, 25, 15, 30, 20, 35, 5])
mean_value = np.mean(data)
new_array = data[data > mean_value]
print("New array with elements greater than the mean:", new_array)


New array with elements greater than the mean: [25 30 35]


In [23]:
import numpy as np

# Generate a 2D array with random integers between 1 and 100
array_2d = np.random.randint(1, 101, size=(5, 4))

# Extract rows where the sum of elements in the second column is greater than 150
sums = np.sum(array_2d[:, 1])
result_rows = array_2d[np.sum(array_2d[:, 1]) > 150]

print("Original array:")
print(array_2d)
print("Rows where the sum of elements in the second column is greater than 150:")
print(result_rows)


Original array:
[[ 28  87   4  21]
 [  1  35  56  35]
 [ 17  32  49 100]
 [ 37  33  83   3]
 [ 80  36  45  58]]
Rows where the sum of elements in the second column is greater than 150:
[[[ 28  87   4  21]
  [  1  35  56  35]
  [ 17  32  49 100]
  [ 37  33  83   3]
  [ 80  36  45  58]]]
