In [11]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/da/3c/3ff05c2855eee52588f489a4e607e4a61699a0742aa03ccf641c77f9eb0a/numpy-1.26.2-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 162.5 kB/s eta 0:00:01
     ------------ ------------------------- 20.5/61.2 kB 162.5 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.2 kB 145.2 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.2 kB 150.6 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.2 kB 150.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 137.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 137.9 kB/s eta 0:00:01
     -------------


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: C:\Users\HELLO\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [12]:
import numpy as np

In [14]:
original_array = array('i',[1,3,5,7,9])
print("original_array:", original_array)

iterable = [2,4,6,8,6]

original_array.extend(iterable)
print("extended array:", original_array)


original_array: array('i', [1, 3, 5, 7, 9])
extended array: array('i', [1, 3, 5, 7, 9, 2, 4, 6, 8, 6])


In [15]:
import numpy as np

original_list = [12.23,13.32,100,36.32]
print("original_list", original_list)

myarray= np.array(original_list)
print("one demnsional array:", original_list)

original_list [12.23, 13.32, 100, 36.32]
one demnsional array: [12.23, 13.32, 100, 36.32]


In [20]:
arr = [1,2,3,4,5]

#for acessing the element from the array we used the index like arr[2] in this code output is the 3 a second element of the list or say array
print(arr[2])
#for the add the element in the array we use the .append function 
##arr.append(6)

#for the remove the element from the array we used a .remove funcion 
#arr.remove(4)

print(arr)

3
[1, 2, 3, 4, 5]


In [28]:
import numpy as np

#append adds the multiple element in the array at a same time
arr2 = np.array([1, 2, 3, 4, 5])
arr2= np.append(arr2,[6,7,8,8])

print(arr2)

[1 2 3 4 5 6 7 8 8]


In [39]:
import numpy as np

#array contain only one element
arr=np.array(2)
print("Array with single element:")
print(arr)
print("\n")

#single dimensional array using list in python 
arr1 = np.array([1,2,3,4,5])
print("Single dimension array created from a list : ")
print(arr1)
print("\n")

#Multi-dimensional array(2D)
arr2 = np.array([[1,2,3],[4,5,6]])
print("multi dimensional array:")
print(arr2)
print("\n")

#3D array 
arr3 = np.array([[[1,2,3],[2,3,4],[3,4,5]]]) 
print("3D Arrays :")
print(arr3)
print("\n")

print("Dimensions of the array")
#this for checking that the array dimensons 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr.ndim)


Array with single element:
2


Single dimension array created from a list : 
[1 2 3 4 5]


multi dimensional array:
[[1 2 3]
 [4 5 6]]


3D Arrays :
[[[1 2 3]
  [2 3 4]
  [3 4 5]]]


Dimensions of the array
1
2
3
0
